#general settings
name: My fantastic App
email: andresmontanez@gmail.com
notifications: true
logging: true
verbose_logging: false
scm:
  type: git
  url:  git://github.com/andres-montanez/Zend-Framework-Twig-example-app.git
