#production
deployment:
  user: root
  from: ./
  to: /var/www/vhosts/example.com/www
  excludes:
    - application/data/cache/twig/*
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - s01.example.com
  - s02.example.com
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - symfony2/cache-warmup: { env: prod }
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
    - symfony2/apply-facls:
        httpuser: www-data
        localuser: deployer
        folders:
          - var
          - web
verbose_logging: true
env:
  variables:
    symfony_env: prod
